### ISSUE TITLE
Frame ordering for Request Stream

### ISSUE THREAD

**Issue by krisskross** [ReactiveSocket/reactivesocket-aeron-rxjava#24]
There seems to be a problem with frame ordering for Request Streams. I can see frames arrive unordered to the client and sometimes onComplete arrive before the last element in the stream. 

The [protocol](https://github.com/ReactiveSocket/reactivesocket/blob/master/Protocol.md) state that the transport must be "Connection-Oriented and preserve frame ordering."

Is this a known issue?

**Comment by stevegury** [comment]
I'm not an expert in Aeron, but based on my limited understanding of it, messages should be given to the application in order.
@robertroeser @tmontgomery may know better.

**Comment by tmontgomery** [comment]
@stevegury is correct. Aeron provides fragments on streams in the order in which the publication sent them.

**Comment by krisskross** [comment]
Ill look into it more. See if I can reproduce in an isolated test.

**Comment by krisskross** [comment]
Server echo 1,2,3 to client for each request stream and the test output this sequence for each round.

https://gist.github.com/krisskross/369abc3e164057947b08

**Comment by robertroeser** [comment]
I'll take a look. Might have something to do with how it queues the data before sending it.

**Comment by robertroeser** [comment]
@krisskross I took a look and it appears to be a problem. Been focusing on request/response right now but will get back to this.

**Comment by krisskross** [comment]
Ok, did you find where and why the messages are reordered?

**Comment by robertroeser** [comment]
No I thought it might have something to do with the ManyToMany queue, or onNext in the subscriber. I synchronized them both, but the problem persisted. Need to spend some more time digging around to see what is causing this.

**Comment by krisskross** [comment]
If you want, I might have some time to spare helping you.

**Comment by krisskross** [comment]
RequestStream ordering works with ```Constants.CONCURRENCY``` set to 1.

If I understand correctly ```Constants.CONCURRENCY``` number of Aeron Subscriptions are created, each paired up with a Scheduler Worker and an Action that continuously poll the subscription. I assume all Subscriptions get all Frames (they subscribe to same Aeron Publication) and the count header indicate which FragmentHandler should consume each Frame.

So I guess the race condition is between consuming Subscriptions, where if one is faster than the other causes this behavior.

**Comment by robertroeser** [comment]
That sounds like the problem. Yes each thread scans the Aeron subscriptions and mod the message count to decide if they consume message or not. Originally the client was single threaded but I thought it play nicer with Netty/RXJava if the client could have more than one thread.

So I guess one option would be to make the client single threaded again. That would get rid of the problem.  Either that or keep track of the previous messages and maintain order.

**Comment by tmontgomery** [comment]
It's worth trying a single threaded perf test and see how it performs.

**Comment by krisskross** [comment]
Here's the ping pong example with 1 and 2 threads. Keep in mind that my computer is quite old (```3.16.0-4-amd64, Linux Intel(R) Core(TM)2 Quad CPU Q6600 @ 2.40GHz```) and the test was run from within IntelliJ.

![pingpong](https://cloud.githubusercontent.com/assets/414023/11668004/3278f4d6-9df5-11e5-8214-ddd630ec0870.png)

**Comment by robertroeser** [comment]
Makes sense - I remember it working better when it was on one thread. Could make it the clients responsibility if they want to schedule work on to different threads after a request has been received.

**Comment by krisskross** [comment]
I was thinking the same thing. 

As you might have guessed, i'm quite interested in this project. I was talking to @stevegury earlier about it and can probably spend a few hours per week on it if you want some extra help? 

Are you open to PR's?

**Comment by robertroeser** [comment]
@krisskross Sure that would be great. Totally open to pull requests.

**Comment by krisskross** [comment]
Great! I'll give this a go then.

I noticed that there aren't many tests yet. What's your plan on testing?

**Comment by robertroeser** [comment]
Need to start adding more unit tests. There's a test project you can use for integration testing too.
